application: jaco-test-test
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "0s"

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /vendor
  static_dir: vendor

- url: /assets
  static_dir: assets

- url: /cron
  script: src.app.wsgi
  login: admin

- url: /.*
  script: src.app.wsgi

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^/.idea/.*$